vsphere_server        = "192.168.1.159"
vsphere_datacenter    = "Home-DC"
vsphere_lin_cluster   = "Home"
vsphere_win_cluster   = "Home"
vsphere_lin_datastore = "vSAN-Cluster"
vsphere_win_datastore = "vSAN-Cluster"
vsphere_network       = "lab-trunk"
vsphere_folder        = "Templates"