vsphere_server        = "mikevct02.miked.lab"
vsphere_datacenter    = "home-dc"
vsphere_lin_cluster   = "home"
vsphere_win_cluster   = "home"
vsphere_lin_datastore = "truenas-nfs1"
vsphere_win_datastore = "truenas-nfs1"
vsphere_network       = "management"
vsphere_folder        = "templates"